nengo/nengo-spa

examples/associative_memory.ipynb
nengo_spa/__init__.py
nengo_spa/assoc_mem.py
nengo_spa/selection.py
nengo_spa/tests/test_assoc_mem.py
nengo_spa/tests/test_selection.py

(This PR has been moved here from nengo/nengo#1253. The discussion from that PR has not been copied over.)
This PR introduces a rewritten associative memory for the `new-spa`.
Compared to previous implementations where the `AssociativeMemory` implemented all possible variants, I split up different possible implementations.
The core networks that can be used to implement something like an associative memory are found in `selection.py`. These are a simple array of thresholding ensembles (`ThresholdingArray`), a basic WTA (`WTA`) with lateral inhibition, and the independent accumulator (`IA`) network submitted to CogSci. All these core networks are standard Nengo networks because they don't operate on semantic pointers, but each dimension represents a potential …

Rewrite associative memory.

---

nengo_spa/__init__.py
nengo_spa/actions.py
nengo_spa/assoc_mem.py
nengo_spa/basalganglia.py
nengo_spa/bind.py
nengo_spa/compare.py
nengo_spa/exceptions.py
nengo_spa/input.py
nengo_spa/network.py
nengo_spa/product.py
nengo_spa/scalar.py
nengo_spa/spa_ast.py
nengo_spa/state.py
nengo_spa/tests/test_actions.py
nengo_spa/tests/test_assoc_mem.py
nengo_spa/tests/test_basalganglia.py
nengo_spa/tests/test_bind.py
nengo_spa/tests/test_compare.py
nengo_spa/tests/test_cortical.py
nengo_spa/tests/test_input.py
nengo_spa/tests/test_network.py
nengo_spa/tests/test_spa_ast.py
nengo_spa/tests/test_state.py
nengo_spa/tests/test_thalamus.py
nengo_spa/thalamus.py
nengo_spa/utils.py

Addresses nengo/nengo#1133.
There is no distinction between `spa.SPA` and `spa.Module` anymore. Furthermore, `spa.Module` can be used like any other `nengo.Network`. Thus, this renames `spa.Module` to `spa.Network`. If you intend to use SPA functionality, you can just switch to use `spa.Network` instead of `nengo.Network` everywhere.
none
unit tests still pass
It's just the renaming and adjusting doc strings accordingly. Hopefully, quick to review even though many lines have been touched.
**Checklist:**
- [n/a] I have added tests to cover my …

Rename spa.Module to spa.Network.

---

nengo_spa/compare.py
nengo_spa/networks/circularconvolution.py
nengo_spa/networks/tests/test_circularconv.py
nengo_spa/state.py
nengo_spa/tests/test_actions.py
nengo_spa/tests/test_bind.py
nengo_spa/tests/test_state.py
nengo_spa/tests/test_thalamus.py

This improves the accuracy of most SPA components by setting intercept and evaluation point distributions. For details see
[The Influence of the Intercept Distribution on Representation in the NEF](http://localhost:8890/notebooks/The%20influence%20of%20the%20intercept%20distribution%20on%20representation%20in%20the%20NEF.ipynb). Note, that this achieves accuracies comparable or better to what I presented [in this paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0149928), but doesn't require any prior optimization step.
none
Tests still pass, in some tests the tolerances needed to be adjusted. This is either an issue of the tolerances being too tight or because many of the …

Implement spaopt.

---

CHANGES.rst
nengo_spa/ast.py
nengo_spa/exceptions.py
nengo_spa/modules/tests/test_cortical.py
nengo_spa/modules/tests/test_thalamus.py
nengo_spa/network.py
nengo_spa/tests/test_network.py
nengo_spa/vocab.py

This PR improves some error messages to fix #32 and #34. As this touches `spa.Network.get_network_input` and `spa.Network.get_network_output`, I used this to also refactor these functions to reduce code duplication and make the implementation slightly simpler.
There is one exception, when a `spa.Network` attribute gets reassigned, that I completely removed because it seems to be unnecessary. I think the reassignment was only a problem in the legacy SPA, but I'm not entirely sure for the initial reason to introduce this exception. Tagging @Seanny123 and @tcstewar who might remember more details. Also, see description of commit d82bab8940fcbdc8ac9de3796171710ccc29886c.
In #29, @ikajic noted that an associative memory gives a misleading exception when the output …

Improve error messages

---

CHANGES.rst
nengo_spa/modules/tests/test_cortical.py
nengo_spa/networks/circularconvolution.py

Benchmarking is hard and I screwed up. The circular convolution wasn't nearly as accurate as it was supposed to be because I only validated the choice of distributions on 50 neurons per dimensions. The choice proposed in this PR is validated on 50 and 200 neurons per dimensions and also for convolution of random + unitary vector, random + random vector, unitary + unitary vector.
[I updated the corresponding section in the intercept distribution notebook.](https://github.com/ctn-waterloo/internal_tech_reports/blob/master/The%20influence%20of%20the%20intercept%20distribution%20on%20representation%20in%20the%20NEF.ipynb)
@rworr, this might be relevant to you.
none
Validation done elsewhere, the linked …

Fix spaopt

---

CHANGES.rst
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocab.py

For the first vector that was added to a vocabulary the transform would not be applied. For examples `vocab.populate('A.unitary()')` would not produce a unitary vector if no other vectors have been added before.
none
Added a regression test.
**Checklist:**

Fix transforms on first vector in vocab.

---

nengo_spa/networks/tests/test_identity_ensemble_array.py

The `IdentityEnsembleArray` network was missing a test which is added in this PR.
Note that the dimensionality in that test chosen so that the test would fail for a `spa.State(d, represent_identity=False)`.
Closes #24.
Last PR before the 0.2 release. :)
none
**Checklist:**

Add test for IdentityEnsembleArray network.

---

CHANGES.rst
nengo_spa/__main__.py
nengo_spa/main.py
nengo_spa/resources.py
nengo_spa/tests/test_examples.py
nengo_spa/tests/test_main.py
nengo_spa/tests/test_resources.py

Examples can now be extracted with `python -m nengo_spa
extract-examples <destination>`.
Addresses #7. This doesn't do the documentation part yet because the documentation still needs to be updated, is currently not included in the distribution, and not published online.
none
Added tests and tested manually.
**Checklist:**

Add cmd interface to extract examples.

---

CHANGES.rst
nengo_spa/pointer.py
nengo_spa/tests/test_pointer.py

Odd vector lengths would produce output vectors smaller by one element.
Fixes #52.
none
added odd vector dimensionalities to relevant tests
**Checklist:**

Fix FFT operation for odd vector lengths.

---

CHANGES.rst
nengo_spa/networks/identity_ensemble_array.py
nengo_spa/networks/tests/test_identity_ensemble_array.py

Adds `add_output` and `add_neuron_output` methods to `IdentityEnsembleArray` to provide the same API as `EnsembleArray`.
none
added new tests
**Checklist:**

Add output methods to IdentityEnsembleArray

---

CHANGES.rst
nengo_spa/__init__.py
nengo_spa/network.py
nengo_spa/tests/test_network.py

This makes it easier to inhibit complete networks, especially those with a lot of ensembles like `spa.State`.
none, though this is based on nengo/nengo#1288.
Added a test.
**Checklist:**

Add function to create inhibition node.

---

CHANGES.rst
nengo_spa/actions.py
nengo_spa/ast.py
nengo_spa/tests/test_network.py
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocab.py

This PR makes a couple of improvements to the vocabulary translation mechanism.
* Missing keys in the target vocabulary will be properly ignored when `populate=False`. This fixes #56.
* Adds a solver argument proposed by @arvoelke that can give slightly better transformation matrices.
To make it possible to use the solver argument in action rules, I imported the whole nengo name space into the action rule built-ins. But it occured to me that this cannot be the final solution because solvers might be defined outside of nengo and these solvers should be usable to. However, making all globals accessible is also problematic because names can refer to modules or semantic pointers and at parse time this can currently not be determined (technically it should be …

Translate improvements

---

CHANGES.rst
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocab.py

This allows easier handling of situations where a `';'.join(keys)` results in an empty string. We decided at the last dev meeting to not raise an error in this case.
none
Added ad test.
**Checklist:**

Allow empty string in Vocabulary.populate().

---

nengo_spa/actions.py
nengo_spa/compiler/ast_nodes.py
nengo_spa/compiler/tests/test_ast.py

Closes #74.
none
existing tests
**Checklist:**

Remove unused root_network argument from infer_types.

---

nengo_spa/modules/tests/test_assoc_mem.py
nengo_spa/modules/tests/test_thalamus.py
nengo_spa/networks/tests/test_selection.py
nengo_spa/tests/test_network.py

Fixes tests run with `--slow` and the `--plots` argument. Note that examples marked as `slow` will still fail. I am planning to fix this in the upcoming milestone that focusses on documentation.
nengo/nengo#1369 is required to use the `--plots` argument.
by running the tests
**Checklist:**

Test fixes before 0.3 release

---

CHANGES.rst
nengo_spa/compiler/ast.py
nengo_spa/compiler/tests/test_ast.py

Fixes #92. I was overzealous in removing whitespace from reconstructed expressions.
none
added a test
**Checklist:**

Do not strip all whitespace from expressions.

---

CHANGES.rst
nengo_spa/compiler/ast.py
nengo_spa/networks/selection.py

Fixes unused arguments reported in #94.
1. Removed the argument in `ConstructionContext` as it is not used at all anymore.
2. Properly pass on `intercept_width` in IA.
none
existing tests
**Checklist:**

Fix unused arguments

---

CHANGES.rst
nengo_spa/compiler/ast_nodes.py
nengo_spa/tests/test_actions.py

Allows actions without any effect by using Python's `pass` keyword:
```python
spa.Actions('''
ifmax 0.5:
pass
''')
```
Fixes #101.
none
added a test
**Checklist:**

Allow noop actions with pass keyword.

---

.travis.yml
CHANGES.rst
README.rst
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocab.py
requirements.txt
setup.py

Fixes the validation of vocabulary related parameters. This was necessary as the `validate` and `__set__` methods on parameters were replaced by a `coerce` method in Nengo 2.5. This also bumps the minimum Nengo version for nengo_spa to 2.5.
Fixes #95.
none
added tests
**Checklist:**

Fix validation of vocab related params.

---

nengo_spa/tests/test_vocabulary.py
tox.ini

Do not depend on `nengo.utils.testing.warns` which has been removed in the Nengo development version and filter irrelevant warnings.
Closes #123.
none
ran the tests
**Checklist:**

Fix warnings related things

---

nengo_spa/actions.py
nengo_spa/modules/tests/test_thalamus.py
nengo_spa/network.py
nengo_spa/tests/test_actions.py

Allows the naming of ifmax actions by providing an optional string as first argument to `ifmax`.
Furthermore, `ActionSelection` implements the dictionary interface. This allows to get the names with the `keys()` method (in some context the result might need an explicit cast to `list(action_sel.keys())`). Actions without a name will be assigned an integer index in this sequence. `ActionSelection` can either be indexed with the string names or integer indices to retrieve the corresponding utility input nodes.
Closes #132.
#68 should be rebased once this PR has been merged.
Added a test.
- New feature …

Naming of ifmax actions

---

nengo_spa/modules/tests/test_transcode.py
nengo_spa/modules/transcode.py

With the new syntax, `SemanticPointer` can track their vocabulary. This makes the `vocab` argument in `Transcode` functions unneccessary as it can be retrieved from the Semantic Pointer that is passed in.
Cherry-picked the commit from my local `docs` branch as it touches actual code and should be reviewed separately. Thus the same commit might at some point appear in PR #68.
existing tests
- Breaking change (fix or feature that causes existing functionality to change)
**Checklist:**
- [n/a] I have included a changelog …

Remove unnecessary argument in Transcode functions.

---

CHANGES.rst
nengo_spa/ast/symbolic.py
nengo_spa/ast/tests/test_symbolic.py

That is, allow spa.sym(expr) where expr is a string with the expression. This allows to write
```python
spa.sym('A + B * C')
```
instead of
```python
spa.sym.A + spa.sym.B * spa.sym.C
```
Closes #138.
none
added a test
**Checklist:**

Add complex symbolic expression syntactic sugar.

---

CHANGES.rst
nengo_spa/vocab.py

When the max similarity criterion in a vocab is violated, it is useful to know what the actual max. simularity is.
Closes #117.
none
```python
import nengo_spa as spa
v = spa.Vocabulary(32)
for i in range(30):
v.populate('V' + str(i))
```
**Checklist:**

State similarity in max similarity warning.

---

CHANGES.rst
docs/examples/custom_module.ipynb
nengo_spa/network.py
nengo_spa/tests/test_actions.py

Allowing standard Nengo objects for scalars in action rules simplifies writing these rules, especially when routed by the action selection system. (Otherwise connections and gates have to be created manually.)
none
added a test
**Checklist:**

Allow scalar Nengo objects in action rules

---

nengo_spa/actions.py
nengo_spa/ast/base.py
nengo_spa/ast/tests/test_dynamic.py
nengo_spa/modules/assoc_mem.py
nengo_spa/modules/bind.py
nengo_spa/modules/compare.py
nengo_spa/modules/product.py
nengo_spa/modules/scalar.py
nengo_spa/modules/state.py
nengo_spa/modules/thalamus.py
nengo_spa/modules/transcode.py
nengo_spa/network.py
nengo_spa/pointer.py
nengo_spa/tests/test_actions.py

This is an attempt to improve the naming and grouping of modules; mainly for a better display in the Nengo GUI. 
* All Nengo SPA modules get a default label. This label, unfortunately, takes precedence even when the module is assigned to a variable in Nengo GUI, i.e. `name = spa.State(64)` will display the name 'State' in Nengo GUI, not 'name'. The obvious workaround is `name = spa.State(64, label='name')`.
* Symbolic expression will display as such under the generated nodes (this was already the case prior to this PR). Example: `spa.sym.A * spa.sym.B * 0.3' will display as 'A*B*0.3'.
* Non-symbolic Semantic Pointer nodes will be label with 'Semantic Pointer (XXd)` where XX is the dimensionality.
* The utility nodes for basal ganglia inputs (the `ifmax` return …

Improve network names and grouping

---

CHANGES.rst
nengo_spa/modules/assoc_mem.py
nengo_spa/modules/tests/test_assoc_mem.py

For consistency, this was not working before. Not sure, if we should rather enforce an explicit vocabulary (with better error message) because only pointers already in the vocab at time of instantiation will be considered.
none
added a test
**Checklist:**

Allow integer vocabs for associative memories.

---

CHANGES.rst
docs/examples/intro_coming_from_legacy_spa.ipynb
nengo_spa/modules/tests/test_transcode.py
nengo_spa/modules/transcode.py

This adds support for SemanticPointer and PointerSymbol instances.
Fixes #175.
none
added tests
**Checklist:**

Allow wider variety of Transcode outputs.

---

CHANGES.rst
nengo_spa/network.py
nengo_spa/tests/test_network.py

Closes #174.
Instead of providing an error when accidentally using nengo.Network
and not a spa.Network, this makes it possible to use a nengo.Network.
The main reason the spa.Network was required, was to track the default
vocabularies. This commit adds a dictionary to that allows to store
the default vocabularies associated with root networks.
This is easier than figuring out whether we shoult raise an Exception
(because spa.Network is allowed to be used in nengo.Network by design).
none
added a test
**Checklist:**
- [n/a] I have updated the …

Allow non-SPA networks as root network.

---

nengo_spa/tests/test_types.py
nengo_spa/types.py

The `__ne__` operator is not automatically defined based on `__eq__` in Python 2.
Cherry-picked from #162 because important enough to be fixed no matter whether and when #162 gets merged.
added a test
**Checklist:**

Fix non-equality relationship in type system.

---

CHANGES.rst
nengo_spa/modules/tests/test_assoc_mem.py
nengo_spa/tests/test_actions.py
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocab.py

Because we rely on the Python interpreter for parsing we cannot use Python keywords as Semantic Pointer name. For some reason the test for unicode characters in Semantic Pointer names was commented out even though it shouldn't. Uncommented it and fixed the regex to require a match of the complete name.
Fixes #187.
none
existing and added tests
**Checklist:**

Exclude keywords and unicode from SP names.

---

CHANGES.rst
nengo_spa/network.py
nengo_spa/tests/test_actions.py

Allows unnamed actions without any effects. Fixes #189.
none
added tests
**Checklist:**

Allow dummy actions.

---

CHANGES.rst
docs/examples/associative_memory.ipynb
docs/examples/intro.ipynb
nengo_spa/modules/assoc_mem.py
nengo_spa/modules/tests/test_assoc_mem.py

As discussed [here](https://github.com/nengo/nengo-spa/pull/171#issuecomment-395085499) this makes the `mapping` argument for associative memories required. This makes explicit which vectors are cleaned up and should lead to less surprise that vectors added later to a vocabulary are not included. It also ensures that in the GUI the vectors are added to the vocabulary instead of potentially creating an empty cleanup memory.
Furthermore, as syntactic sugar sequences of strings are allowed as syntactic sugar for `{k: k for k in sequence}`.
based on #171 (that one provides pure bugfixes, this one provides API changes which require a minor release instead of a bugfix release)
added tests
**How long …

Enforce mapping argument on associative memories

---

CHANGES.rst
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocab.py

Addresses #176.
Allows `spa.sym.Zero`, `vocab['Identity']`, and `vocab.parse('AbsorbingElement')` to access special Semantic Pointers. These names won't be listed in `vocab.keys()` or `vocab.vectors`.
none
added a test
**Checklist:**

Add parsing for special Semantic Pointers.

---

CHANGES.rst
docs/examples/associative_memory.ipynb
docs/examples/convolution.ipynb
nengo_spa/__init__.py
nengo_spa/algebras/tests/test_algebras.py
nengo_spa/algebras/tests/test_vtb.py
nengo_spa/ast/tests/test_dynamic.py
nengo_spa/ast/tests/test_symbolic.py
nengo_spa/modules/tests/test_assoc_mem.py
nengo_spa/modules/tests/test_bind.py
nengo_spa/modules/tests/test_superposition.py
nengo_spa/modules/transcode.py
nengo_spa/networks/tests/test_identity_ensemble_array.py
nengo_spa/networks/tests/test_selection.py
nengo_spa/networks/tests/test_vtb.py
nengo_spa/pointer.py
nengo_spa/tests/test_actions.py
nengo_spa/tests/test_examine.py
nengo_spa/tests/test_network.py
nengo_spa/tests/test_pointer.py
nengo_spa/tests/test_vector_generation.py
nengo_spa/tests/test_vocabulary.py
nengo_spa/vector_generation.py
nengo_spa/vocab.py

This PR adds a number of generators to generate vectors for Semantic Pointers. These can be passed to a `Vocabulary` to specify how new Semantic Pointers should be generated. This allows to easily create vocabularies with all unitary, orthogonal, or axis-aligned vectors. It also gives the user the possibility to program custom generation methods.
This removes the possibility to create a random pointer with `SemanticPointer(d)`. Not sure if this has been widely used and if some short-form syntax should be put back in. With this PR one can do `SemanticPointer(next(UnitLengthVectors(d)))`) instead.
Closes #129.
Based on #198 which introduces some changes to the code touched, but it is not essential to this PR.
**How has this been …

Different ways to generate Semantic Pointers

---

CHANGES.rst
nengo_spa/math.py
nengo_spa/tests/test_math.py

This fixes the documentation where one statement was wrong. Also, an exception is raised instead of returning incorrect values, when the calculation fails due to limited floating point precision.
Fixes #203.
none
added assert in the relevant test
Please make sure that the documentation is actually correct and that I didn't confuse myself in the end.
**Checklist:**

Fix prob_cleanup

---

CHANGES.rst
nengo_spa/action_selection.py
nengo_spa/tests/test_action_selection.py

It was failing without a named action.
none
added tests
**Checklist:**

Fix action selection key iteration.

---

CHANGES.rst
nengo_spa/action_selection.py
nengo_spa/ast/dynamic.py
nengo_spa/ast/tests/test_dynamic.py
nengo_spa/semantic_pointer.py
nengo_spa/tests/test_semantic_pointer.py
nengo_spa/tests/test_vector_generation.py

Fixes the problem discovered in #202 that a dot product with a fixed `SemanticPointer` instance creates a compare network which is not needed. This ensures that a transform is used instead.
Furthermore, it fixes a problem where `spa.dot(a, b)` would return a NumPy array instead of a scalar or AST node when `a` was a `SemanticPointer`.
Somewhat related to the the confusion in #202 a label is added for the action utility node.
none
Extended tests except for the label of the utility node.
**Checklist:**
- [n/a] I have …

Fix dot with fixed Semantic Pointer.

---

.ci/test.sh

Set maximum pytest and xdist versions to avoid the tests failing on CI. Newer pytest versions produce warnings with Nengo 2.8 (i.e. those cannot be fixed in Nengo SPA) and newer xdist versions are incompatible with the chosen pytest version.
none
Waited for CI tests to pass.
**Checklist:**

Fix CI tests

---

CHANGES.rst
nengo_spa/action_selection.py
nengo_spa/tests/test_action_selection.py

Ensure free floating connections are cleared after leaving ActionSelection block.
Fixes #230.
none
added a unit test
**Checklist:**

Ensure free floating connections are cleared

---

.appveyor.yml
.ci/test.sh
.travis.yml
CHANGES.rst
CONTRIBUTING.rst
nengo_spa/conftest.py
nengo_spa/modules/tests/test_bind.py
nengo_spa/modules/tests/test_superposition.py
nengo_spa/networks/matrix_multiplication.py
nengo_spa/networks/tests/test_circularconv.py
nengo_spa/networks/tests/test_selection.py
nengo_spa/tests/test_examples.py
nengo_spa/tests/test_network.py
nengo_spa/tests/test_semantic_pointer.py
setup.cfg
setup.py

This mostly introduces some changes to the test environment
utilizing pytest-plt and pytest-rng. On older Nengo versions
these fixtures will be imported as from Nengo itself as before.
However, we don't support the test command line options
on Nengo versions prior to 3 anymore. All tests (including tests
marked as slow) will run on these versions, but no plots will be
produced. On Nengo 3 these command line options are supported as
before.
Besides that this adds some irrelevant warnings to the ignore list
and fixes an instance where deprecated network inputs have been
used.
Closes #225.
none
Ran the tests.
**Types of …

Ensure Nengo 3 compatibility

---

CHANGES.rst
nengo_spa/modules/associative_memory.py
nengo_spa/modules/basalganglia.py
nengo_spa/modules/bind.py
nengo_spa/modules/compare.py
nengo_spa/modules/product.py
nengo_spa/modules/scalar.py
nengo_spa/modules/state.py
nengo_spa/modules/superposition.py
nengo_spa/modules/thalamus.py
nengo_spa/modules/transcode.py
nengo_spa/networks/circularconvolution.py
nengo_spa/networks/identity_ensemble_array.py
nengo_spa/networks/matrix_multiplication.py
nengo_spa/networks/selection.py
nengo_spa/networks/vtb.py

Given the nengo/nengo-gui#1002 has been merged, not setting any default labels will give more informative labels in the Nengo GUI. This also converts all networks to classes to be more consistent.
none
existing tests
Most lines did just change in indentation (due to __init__ being nested in the class) and have `net` renamed to `self`.
- Breaking change (fix or feature that causes existing functionality to change)
**Checklist:**

Do not set default labels

---

.travis.yml
CHANGES.rst
nengo_spa/__init__.py
nengo_spa/algebras/base.py
nengo_spa/algebras/tests/test_algebras.py
nengo_spa/semantic_pointer.py
nengo_spa/tests/test_semantic_pointer.py
nengo_spa/tests/test_vocabulary.py
nengo_spa/vocabulary.py

Mixing algebras is not supported without explicit casts. Thus raise an exception when this is tried.
SemanticPointe.reinterpret can be used to add the pointer anyways.
Fixes #239.
unit test
**Checklist:**

Ensure SP algebra matches vocab

---

CHANGES.rst
LICENSE.rst
docs/user-guide/spa-intro.rst
nengo_spa/semantic_pointer.py
nengo_spa/tests/test_semantic_pointer.py

Fixes #244. 1 KB was chosen somewhat arbitrarily, but it seems long enough to capture the majority of use cases where someone might want to read the name, while being a cheap amount of memory relative to the resource requirements of the semantic pointer itself and how it will be used.
I considered adding a warning, but it didn't seem important enough to let the user know (the fact that the name is being truncated seems inconsequential for most users)?
Added a unit test similar to the reproducing example from #244.
**Checklist:**

Truncate semantic pointer names to 1 KB

---

CHANGES.rst
nengo_spa/ast/dynamic.py
nengo_spa/ast/symbolic.py
nengo_spa/ast/tests/test_dynamic.py
nengo_spa/ast/tests/test_symbolic.py
nengo_spa/connectors.py
nengo_spa/semantic_pointer.py
nengo_spa/tests/test_semantic_pointer.py

* This adds support for NumPy scalars in binary operations with `SemanticPointer`. Maybe slightly confusingly both `is_array` and `is_number` are true for NumPy scalars and thus evaluation order of these functions matters.
* While implementing this, I noticed that operations on the AST (that is on modules, symbolic Semantic Pointer expression, and the like) should also support NumPy scalars and division (which was implemented in #254).
* I added a test for the NumPy scalars.
* I added a test and the implementation for the division operator.
none
Added and existing unit tests.
- Bug fix (non-breaking …

Support NumPy scalars; further division support

---

CHANGES.rst
docs/examples/spa-sequence.ipynb

The stimulus wasn't connected to the state being sequenced, and so it would randomly break depending on whether the initial state was close enough to some vector in the vocabulary.
Fixes #258.
Ran it locally and tried out a bunch of different seeds and longer simulation times. It always seems to do the right thing now.
**Checklist:**
- [N/A] I have updated the documentation accordingly.
- [N/A] I have added tests to cover my changes.

Fix SPA sequence example

---

setup.cfg
setup.py

Add version constraint to all dependencies to prevent things from breaking randomly (as long as dependencies follow Semantic Versioning), especially in CI builds. Also, allow pytest 6 to fix incompatibility with pytest-xdist 2 in the CI builds.
~This supersedes commit 51bf91b5d686851954d37da8ef64038283f86d57 from PR #263.~
Existing tests and building documentation with minimum versions of dependencies and maximum available versions ~satisfying the constraints~.
**Checklist:**
- [n/a] I have …

Add dependency version constraints

---

.travis.yml
CHANGES.rst
docs/conf.py
docs/modules/nengo_spa.algebras.rst
docs/modules/nengo_spa.networks.rst
docs/modules/nengo_spa.semantic_pointer.rst
docs/modules/nengo_spa.vocabulary.rst
docs/user-guide/algebras.rst
nengo_spa/algebras/__init__.py
nengo_spa/algebras/base.py
nengo_spa/algebras/hrr_algebra.py
nengo_spa/algebras/tests/test_algebras.py
nengo_spa/algebras/vtb_algebra.py
nengo_spa/ast/dynamic.py
nengo_spa/ast/symbolic.py
nengo_spa/ast/tests/test_dynamic.py
nengo_spa/ast/tests/test_symbolic.py
nengo_spa/connectors.py
nengo_spa/modules/tests/test_bind.py
nengo_spa/networks/tests/test_vtb.py
nengo_spa/networks/vtb.py
nengo_spa/semantic_pointer.py
nengo_spa/tests/test_semantic_pointer.py
nengo_spa/version.py
nengo_spa/vocabulary.py

So far NengoSPA assumed that all special elements (i.e. identity, zero, absorbing element, and inverse) of an algebra are two-sided, i.e. can be applied to either side in the binding with the same effect. While this is true for HRR/circular convolution, it does not hold in general. In particular, VTB only has a right identity and inverse(*), and by transposing the VTB-matrix a variant is obtained where there are only a left identity and inverse.
This PR changes things, so that one can explicitly ask for the left, right or two-sided inverse. In most methods this is done via a new `sidedness` argument taking a corresponding enum value. For backwards compatibility this argument is `ElementSidedness.TWO_SIDED` by default. Furthermore, for VTB this value will return …

Support to differentiate the sidedness of algebra special elements

---

CHANGES.rst
nengo_spa/ast/expr_tree.py
nengo_spa/ast/tests/test_expr_tree.py
nengo_spa/semantic_pointer.py
nengo_spa/tests/test_semantic_pointer.py
nengo_spa/tests/test_vocabulary.py

Instead of immediately constructing a string for the SemanticPointer
name, this uses the expr_tree classes to construct a syntax tree.
This enables keeping track of operation precedence and allows to
render a name with only the necessary parenthesis increasing the
readability of SemanticPointer names.
Furthermore, this implements a visitor for this syntax tree to limit the
rendered length while preserving correctness of the parenthesis.
Closes #255.
none
* added unit tests
* modified the test for maximum name length accordingly
- Lengthy (more than 150 lines changed or changes are complicated)
- New feature (non-breaking change which …

Generate better SemanticPointer names

---

CHANGES.rst
docs/modules/nengo_spa.algebras.rst
docs/modules/nengo_spa.networks.rst
nengo_spa/algebras/__init__.py
nengo_spa/algebras/tests/test_algebras.py
nengo_spa/algebras/tvtb_algebra.py
nengo_spa/algebras/vtb_algebra.py
nengo_spa/conftest.py
nengo_spa/networks/__init__.py
nengo_spa/networks/tests/test_tvtb.py
nengo_spa/networks/tvtb.py

Transposed Vector-derived Transformation Binding (TVTB) uses the same binding method as VTB, but transposes the derived matrix. This makes the identity and inverse two-sided.
Based on #265 and PR is against that branch to get the relevant diff.
Mostly existing generic algebra tests, but tests for the VTB network have been copied and used to test the TVTB network.
I'd suggest to take a look at `TvtbAlgebra` first (compare it to `VtbAlgebra`) and then look at the `TVTB` network (and compare it to the `VTB` network).
- New feature (non-breaking change which adds …

Implement TVTB algebra

---

CHANGES.rst
docs/modules/nengo_spa.vector_generation.rst
nengo_spa/__init__.py
nengo_spa/modules/tests/test_cortical.py
nengo_spa/tests/test_vector_generation.py
nengo_spa/vector_generation.py

This introduces two new vector generators based on #271.
* ``VectorsWithProperties`` adds a more convenient method to generate a larger number of vectors with desired properties (positive and/or unitary). In theory the less general ``UnitaryVectors`` generator could be implemented with the ``VectorsWithProperties``, however, this would be a breaking change because ``UnitaryVectors`` might be used with an older algebra implementation that does not implement ``create_vectors``.
* `EquallySpacedPositiveUnitaryHrrVectors` allows to create positive, unitary HRR vectors with an equal spacing around the hyper-circle those vectors lie on.
This PR closes #284.
based on #271 
Further PRs to make the #271 features available from the …

New vector generators
