- nengo_spa/conftest.py
- nengo_spa/network.py
- nengo_spa/tests/test_network.py
Allows to copy nengo_spa networks. Originally an issue reported for legacy SPA in nengo/nengo#1266.
Based on nengo/nengo#1271.
Added a unit test.
- Quick (less than 40 lines changed or changes are straightforward)d)
**Checklist:**
> Allow copying of nengo_spa.Network.

- nengo_spa/assoc_mem.py
Even though the documentation needs to be overhauled, this might be easy to forget or miss later on.
This is analogous to nengo/nengo#1215.
pure documentation change
**Checklist:**
> Fix incorrect associative memory documentation.

- nengo_spa/actions.py
- nengo_spa/modules/compare.py
- nengo_spa/modules/input.py
- nengo_spa/modules/tests/test_basalganglia.py
- nengo_spa/network.py
- nengo_spa/networks/tests/test_circularconv.py
- nengo_spa/tests/test_actions.py
This removes a bunch of code that only existed to support legacy syntax and API from the old `nengo.spa`. One particular change is to not track the SPA networks manually anymore, but just look at the network's attribute (each module has to be assigned as an attribute anyways to be accesible in action rules).
none
Existing tests still pass.
**Checklist:**
> Remove deprecated stuff.

- CHANGES.rst
This adds changelog entries for merged PRs where I forgot to add them.
none
n/a
**Checklist:**
> Add missing changelog entries.

- CHANGES.rst
The links in the changelog where pointing to the Nengo core repository and not the nengo_spa repository as they should. This PR fixes that.
none
n/a
**Checklist:**
> Fix links in changelog.

- CHANGES.rst
- nengo_spa/examples/intro_coming_from_legacy_spa.ipynb
- nengo_spa/modules/tests/test_cortical.py
- nengo_spa/tests/test_examples.py
- nengo_spa/tests/test_vocabulary.py
- nengo_spa/vocab.py
This adds a tutorial describing what changed in nengo_spa compared to the legacy SPA implementation. My presentation on Friday will be based on this.
There are a few spots where links are missing because the documentation that should be linked to has not been written (or updated) yet. I think this PR should be merged anyways because adding all the remaining documentation is a larger job that will be done in the (hopefully near) future.
none
Ran all cells in the notebook manually. There is also a test that checks that no exceptions are raised in the notebook. I will add a commit to add the notebook to the list of slow tests once the CI builds have completed to not waste time on this for each commit, …
> Add tutorial for transition from legacy SPA.

- README.rst
Fixes #41.
none
checked that new link works
**Checklist:**
> Fix link in AppVeyor build badge.

- CHANGES.rst
- nengo_spa/actions.py
- nengo_spa/tests/test_actions.py
To avoid having unnecessary networks floating around.
Fixes #42.
Potentially touches the same code as #59, but there shouldn't be many conflicts.
added a test
**Checklist:**
> Only create basal ganglia and thalamus if required.

- README.rst
At the moment the readme display the badge for the last build which will be some development branch in general. It would be better to display the badge for the master branch (default branch).
none
Looked at the rendered view of the readme and clicked the badge to check the link.
**Checklist:**
> Use AppVeyor badge for master branch.

- nengo_spa/networks/circularconvolution.py
Analoguous to nengo/nengo#1337. Removes memoize because it doesn't give a real performance increase, but can give non-obvious side effects in some specific situations.
nengo/nengo#1337
existing tests
**Checklist:**
> Remove usage of memoize.

- nengo_spa/compiler/grammar.py
- nengo_spa/compiler/tests/test_grammar.py
Fixes #81.
none
added a test case, ran the code provided in the issue.
**Checklist:**
> Allow leading comments in action rules.

- CHANGES.rst
- nengo_spa/modules/basalganglia.py
- nengo_spa/modules/thalamus.py
Addresses #84.
none
Checked the label in Nengo GUI.
**Checklist:**
Incorporate names?
> Assign default label to basal ganglia.

- CHANGES.rst
- nengo_spa/compiler/ast_nodes.py
This improves some error messages.
1. Clearer message when something is used as input/output without being declared as such.
2. Include information about the effect where a type error occurs in the exception.
none
tried out the examples in #82 (though those needed to be edited to actuall get the input and outputs wrong)
**Checklist:**
> Better errors

- CHANGES.rst
- nengo_spa/network.py
- tox.ini
Fix relevant warnings and hide irrelevant warnings to have less noise and make future relevant warnings more salient.
none
ran the tests
**Checklist:**
> Fix warnings in tests.

- CHANGES.rst
- nengo_spa/actions.py
- nengo_spa/tests/test_actions.py
Resolves #80.
Created new tests to check for both presence and absence of `bg` and `thalamus`.
**Checklist:**
> Added accessors for all bgs and thals

- CHANGES.rst
- nengo_spa/compiler/grammar.py
- nengo_spa/compiler/tests/test_grammar.py
Fixes #107.
none
added a test case
**Checklist:**
> Allow empty spa.Actions.

- appveyor.yml
Fixes the failing Appveyor build analogous to nengo/nengo#1382.
none
not tested, waiting for Appveyor build to complete
**Checklist:**
> Fix build on Appveyor by using newer Python.

- nengo_spa/compiler/ast.py
- nengo_spa/compiler/grammar.py
- nengo_spa/compiler/tests/test_ast.py
- nengo_spa/compiler/tests/test_grammar.py
- nengo_spa/tests/test_actions.py
Fixes #102.
none
added test case
**Checklist:**
> Fix comments at start of indented blocks.

- .travis.yml
- nengo_spa/examples/associative_memory.ipynb
- nengo_spa/examples/convolution.ipynb
The title says pretty much everything.
Same change as nengo/nengo#1394.
**Checklist:**
> Fix Travis CI builds by making conda install quiet.

- nengo_spa/tests/test_pointer.py
Fix failing AppVeyor test.
none
Waiting for AppVeyor build to pass.
**Checklist:**
> Fix SemanticPointer str representation test.

- CHANGES.rst
- nengo_spa/network.py
- nengo_spa/tests/test_network.py
Allow the configuration of instance parameters with `nengo_spa.Network.config`.
Fixes #112.
none
added test case
**Checklist:**
> Allow configuration of instance parameters.

- appveyor.yml
Install pywinpty with conda.
To avoid error with too long filename when installed as dependency by
pip.
- Lengthy (more than 150 lines changed or changes are complicated)
- Breaking change (fix or feature that causes existing functionality to change)
**Checklist:**
> Fix AppVeyor build.

- .pylintrc
- nengo_spa/compiler/ast.py
- nengo_spa/compiler/parsing.py
- nengo_spa/conftest.py
- nengo_spa/modules/transcode.py
This puts this file back in sync with Nengo's pylintrc.
Ran `pylint nengo_spa`.
**Checklist:**
> Update enabled pylint checks.

- nengo_spa/modules/assoc_mem.py
- nengo_spa/modules/tests/test_assoc_mem.py
- nengo_spa/networks/selection.py
- nengo_spa/networks/tests/test_selection.py
- requirements-test.txt
Resolves #118. Basically, the `input_reset` of the module wasn't being declared properly. I fixed this and added a test.
- Lengthy (more than 150 lines changed or changes are complicated)
Read the test first, to make sure I'm testing everything properly.
**Checklist:**
> Fixed IA associative memory

- appveyor.yml
Numpy 1.13 is supposed to work (opposed to 1.14), let's try to pin it and see if that fixes the build.
none
AppVeyor build passed.
**Checklist:**
> Workaround for broken AppVeyor build.

- .travis.yml
- README.rst
- nengo_spa/vocab.py
- requirements.txt
- setup.py
~~Nengo 2.6 has been released a while back and allows us to simplify some code that has been marked with an according TODO.~~
When Nengo 2.7 is released, this can be merged.
This PR bumps the Nengo requirement and simplifies that code.
none
existing tests
**Checklist:**
> Bump Nengo requirment to 2.7 and simplify some code

- README.rst
> Update readme with new documentation.

- docs/getting_started.rst
Fix a warning.
none
doc change only
**Checklist:**
> Fix warning about double ref name in docs.

- README.rst
Fixes the links to the badges in the readme (some where broken due to renaming the repository).
none
Tried the URLs.
**Checklist:**
> Build badge

- README.rst
- docs/_static/full-light.svg
- docs/conf.py
none
looked at the rendering of the readme and documentation
**Checklist:**
> Add logos to documentation and readme

- nengo_spa/ast/tests/test_dynamic.py
- nengo_spa/modules/tests/test_thalamus.py
They just create empty plots in the tests.
none
Ran the tests with `--plots --slow` and checked for empty plots.
**Checklist:**
> Remove unused plt fixtures.

- MANIFEST.in
- docs/examples/custom_module.ipynb
- docs/examples/intro_coming_from_legacy_spa.ipynb
- docs/examples/spa_parser.ipynb
- nengo_spa/network.py
- setup.py
The `global-exclude *.tox*` in the `MANIFEST.in` did not work and my `.tox` directory was stilll included in the distribution. `prune *.tox` does work.
Also adds the URL to the documentation to `setup.py`.
none
`python setup.py sdist bdist_wheel`
**Checklist:**
> Fix manifest

- MANIFEST.in
Still had `.ropeproject` in my source distribution.
none
`python setup.py sdist bdist_wheel`
**Checklist:**
> Exclude all hidden dirs except .ci in dist.

- README.rst
> Fix the logo on PyPI.

- docs/conf.py
> Add githubpages Sphinx extension.

- CHANGES.rst
- nengo_spa/tests/test_types.py
- nengo_spa/types.py
Addresses #131.
none
added test
**Checklist:**
> Improve incompatible types error message.

- .pylintrc
- nengo_spa/ast/symbolic.py
- nengo_spa/modules/__init__.py
- nengo_spa/modules/tests/test_bind.py
- nengo_spa/networks/tests/test_circularconv.py
- nengo_spa/vocab.py
Closes #96.
none
Ran `pylint nengo_spa`.
**Checklist:**
> Update .pylintrc to match core Nengo's .pylintrc.

- CHANGES.rst
- nengo_spa/vocab.py
Closes #163. Naming vocabularies is useful for debugging type problems in your models.
none
tested manually
**Checklist:**
> Allow to name vocabularies.

- .ci/test.sh
Fixes #172 by forcing conda to use MKL to keep CI tests within time limits.
none, except fixing the Travis-CI tests
Travis-CI
**Checklist:**
> Try to force usage of MKL.

- docs/examples/associative_memory.ipynb
- docs/examples/intro.ipynb
Resolves #167 and #168.
**Checklist:**
> Updated Intro and Association Memory docs.

- CHANGES.rst
- nengo_spa/ast/symbolic.py
- nengo_spa/ast/tests/test_symbolic.py
Fixes #169.
none
added a test
**Checklist:**
> Implement reinterpret for PointerSymbol.

- CHANGES.rst
- nengo_spa/ast/base.py
- nengo_spa/ast/tests/test_symbolic.py
- nengo_spa/pointer.py
- nengo_spa/tests/test_pointer.py
Fixes #192.
none
added tests
**Checklist:**
> Prevent SPA operations with array.

- nengo_spa/modules/tests/test_basalganglia.py
- nengo_spa/tests/test_actions.py
- nengo_spa/tests/test_examples.py
To have tests complete faster.
none
n/a
**Checklist:**
> Mark more slow tests.

- nengo_spa/algebras/vtb_algebra.py
Turns out the swapping and inversion matrices are identical.
Made this realization thanks to @arvoelke.
none
existing tests
**Checklist:**
> Remove uneccessary VTB code.

- nengo_spa/algebras/vtb_algebra.py
Probably more efficient than the for loop. Also, fewer code lines.
Thanks to @arvoelke for coming up with this, see [this comment](https://github.com/nengo/nengo-spa/pull/207) for details.
none
existing tests
**Checklist:**
> Simplify code for VTB inversion matrix.

- CHANGES.rst
- nengo_spa/modules/state.py
- nengo_spa/modules/tests/test_state.py
Because it only optimizes for the circular convolution identity, but not VTB identity or identity for potential other binding operations.
none
existing updated tests
- Breaking change (fix or feature that causes existing functionality to change)
**Checklist:**
> Rename represent_identity to represent_cc_identity.

- docs/conf.py
- nengo_spa/modules/state.py
Mirrors the change to `spa.State` documentation from the soon-to-be-deprecated `nengo/spa/state.py`: https://github.com/nengo/nengo/pull/1471.
Copies the one commit from https://github.com/nengo/nengo/pull/1471 (with slight modification -- see comment below).
Not applicable.
**Checklist:**
> Improved State documentation

- .ci/test.sh
- .travis.yml
- nengo_spa/connectors.py
- nengo_spa/modules/tests/test_basalganglia.py
- nengo_spa/modules/tests/test_thalamus.py
- nengo_spa/modules/transcode.py
- nengo_spa/networks/identity_ensemble_array.py
- nengo_spa/networks/selection.py
- nengo_spa/tests/test_action_selection.py
- nengo_spa/types.py
- nengo_spa/vocabulary.py
- setup.py
Make the CI builds pass again to unblock other PRs.
Unblocks other PRs that currently do not pass the CI.
CI builds.
**Checklist:**
> Enforce pytest < 4.0

- docs/modules/nengo_spa.vocabulary.rst
- setup.py
Fixes #215.
Fixes #216.
none
build docs and searched for something
**Checklist:**
> Fix search functionality in docs and add missing documentation for vocabulary

- nengo_spa/ast/base.py
- nengo_spa/modules/associative_memory.py
- nengo_spa/modules/basalganglia.py
- nengo_spa/modules/bind.py
- nengo_spa/modules/compare.py
- nengo_spa/modules/product.py
- nengo_spa/modules/scalar.py
- nengo_spa/modules/state.py
- nengo_spa/modules/superposition.py
- nengo_spa/modules/thalamus.py
- nengo_spa/modules/transcode.py
- nengo_spa/network.py
- nengo_spa/networks/circularconvolution.py
- nengo_spa/networks/identity_ensemble_array.py
- nengo_spa/networks/matrix_multiplication.py
- nengo_spa/networks/selection.py
- nengo_spa/networks/vtb.py
Argument was previously not properly documented.
none
Build the docs and looked at it.
**Checklist:**
> Document selection_net_args

- README.rst
Apparently, it was moved ...
none
looked at the rendered readme on this branch
**Checklist:**
> Fix the URL to the Nengo SPA logo in the README.

- setup.py
Motivation and context:**
In order to not have Nengo SPA break when Nengo 3 gets released.
none
trivial change that I did not test.
**Checklist:**
> Be explicit about not supporting Nengo 3 yet.

- CHANGES.rst
- docs/examples/associative_memory.ipynb
- docs/modules/nengo_spa.semantic_pointer.rst
- docs/modules/nengo_spa.vector_generation.rst
- nengo_spa/semantic_pointer.py
This add some things that were missing in the docs, also see #228 
none
build and looked at the documentation
**Checklist:**
> Add missing docs

- CHANGES.rst
- docs/conf.py
Closes #237
none
Tested that old URLs with underscores redirect to the new ones.
**Checklist:**
> Add redirects from old documentation URLs

- docs/user-guide/spa-intro.rst
~none~ ~I guess these issues have also been fixed in #246 ...~ One fixed typo remaining here ...
**Checklist:**
> Fix master

- CHANGES.rst
- nengo_spa/semantic_pointer.py
- nengo_spa/tests/test_semantic_pointer.py
Fixes #249.
none
Added a unit test.
**Checklist:**
> Implement division operator for SemanticPointer

- LICENSE.rst
- Updated link to current sphinx license
The previous sphinx license link no longer exists. Updated the link to the correct license link.
Start with the `LICENSE.rst` file.
**Checklist:**
- [na] I have included a changelog entry.
- [na] I have tested this with all supported devices.
- [na] I have added tests to cover my changes.
- [na] I have run the test suite locally and all tests passed.
> Updated links to sphinx-docs website

- README.rst
We're doing this for all of our repos.
Based on #274.
> Remove TravisCI badge, add versions badges

- docs/conf.py
Certificate verification fails because local issuer certificate is not
included.
none
existing tests
**Checklist:**
> Ignore journals.plos.org in linkcheck

- nengo_spa/tests/test_typechecks.py
I forgot to commit this file as part of d3712e0ecc0ca8b0423a4ef40b6e3127d2ea0d20
(PR #289).
Should have been included in #289.
**Checklist:**
> Add tests for type checks

- README.rst
- docs/conf.py
- docs/modules/nengo_spa.algebras.rst
- docs/pyplots/power_similarity.py
- docs/user-guide.rst
- docs/user-guide/fractional-binding.rst
- nengo_spa/algebras/tvtb_algebra.py
- nengo_spa/algebras/vtb_algebra.py
This adds the user guide documentation for binding powers and signs (PR #271).
Based on #271 implementing the actual feature
Built documentation and looked it.
**Checklist:**
> Documentation for binding powers and signs

- CHANGES.rst
- docs/examples.rst
- docs/examples/learning.ipynb
This has been in the backlog for a long time and [this question in the forum](https://forum.nengo.ai/t/integrating-learning-to-spa/1740) prompted me to finally document this.
This commit closes #16.
none
ran the notebook
**Checklist:**
> Add learning example

- CHANGES.rst
(It's RST not Markdown.)
**Checklist:**
> Fix changelog formatting
